#!/usr/bin/env bash
# Installs, configures, and starts the web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html /var/www/error
chmod -R 755 /var/www
sudo echo 'Hello World!' > /var/www/html/index.html
sudo echo -e "Ceci n'est pas une page" > /var/www/error/404.html
# the server's configuration
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.html index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
		add_header X-Served-By \$hostname;
	}
	if (\$request_filename ~ redirect_me){
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /var/www/error/;
		internal;
		add_header X-Served-By \$hostname;
	}
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
