#!/usr/bin/env bash
# using the for loop, display the content of the current directory
# displays in a list format where only the part of the name after the first dash is displayed

for i in *;
do
    echo "$i" | cut -d'-' -f2
done
