#!/usr/bin/env bash
# gives you information about the school file using the if/else statement

file="school"
if [ -e "$file" ]
then
    echo "$file file exists"
    if [ -s "$file" ]
	then
		echo "school file is not empty"
    else
		echo "school file is empty"
    fi
    if [ -f "$file" ]
	then
		echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
